server:
  port: 8080

spring:
  datasource:
    name: community
    url: jdbc:mysql://1.116.57.190:3306/wan_neng_qiang?useUnicode=yes&characterEncoding=UTF-8&amp&useSSL=false&amp&allowPublicKeyRetrieval=true&amp&serverTimezone=UTC
    username: root
    password: Wn9323252766
    driverClassName : com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 568118859@qq.com
    #授权码
    password: qrtmhefavdgwbfcb
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    host: 127.0.0.1
    port: 6379 #Redis服务器连接端口
    password:  2860576983 #Redis服务器连接密码（默认为空）
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 30000ms #连接超时时间（毫秒）

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.lyh.community.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  file:
#    path: D:/community
    path: /var/