server:
  port: 8080

spring:
  datasource:
    name: community
    url: jdbc:mysql://1.116.57.190:3306/wan_neng_qiang?useUnicode=yes&characterEncoding=UTF-8&amp&useSSL=false&amp&allowPublicKeyRetrieval=true&amp&serverTimezone=UTC
    username: root
    password: Wn9323252766
    driverClassName : com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.lyh.community.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  file:
#    path: D:/community
    path: /var/