DROP DATABASE wall;

CREATE DATABASE wall;

USE wall;

CREATE TABLE `Collect_topic`  (
  `uid` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `tid` INT(4) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`uid`, `tid`) USING BTREE,
  INDEX `tid`(`tid`) USING BTREE
) ENGINE = INNODB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `Comment`  (
  `cid` INT(4) NOT NULL AUTO_INCREMENT,
  `ctime` DATETIME(6) NULL DEFAULT NULL,
  `canonymous` TINYINT(1) NULL DEFAULT NULL,
  `ccontent` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `tid` INT(4) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  PRIMARY KEY (`cid`) USING BTREE,
  INDEX `tid`(`tid`) USING BTREE
) ENGINE = INNODB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `Express_comment`  (
  `uid` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `cid` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `tid` INT(4) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  PRIMARY KEY (`uid`, `cid`) USING BTREE,
  INDEX `cid`(`cid`) USING BTREE
) ENGINE = INNODB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `Like_comment`  (
  `uid` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `cid` INT(4) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`uid`, `cid`) USING BTREE,
  INDEX `cid`(`cid`) USING BTREE
) ENGINE = INNODB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `Like_topic`  (
  `uid` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `tid` INT(4) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`uid`, `tid`) USING BTREE,
  INDEX `tid`(`tid`) USING BTREE
) ENGINE = INNODB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `Module`  (
  `mid` INT(4) NOT NULL AUTO_INCREMENT,
  `mname` CHAR(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `mintro` VARCHAR(10000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  PRIMARY KEY (`mid`) USING BTREE
) ENGINE = INNODB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `Submit_topic`  (
  `uid` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `tid` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `mid` INT(4) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  PRIMARY KEY (`uid`, `tid`) USING BTREE,
  INDEX `tid`(`tid`) USING BTREE
) ENGINE = INNODB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `Topic`  (
  `tid` INT(4) NOT NULL AUTO_INCREMENT,
  `uid` INT(4) UNSIGNED ZEROFILL NOT NULL,
  `ttime` DATETIME(6) NULL DEFAULT NULL,
  `tanonymous` TINYINT(1) NULL DEFAULT NULL,
  `tcontent` VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `mid` INT(4) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  PRIMARY KEY (`tid`) USING BTREE,
  INDEX `mid`(`mid`) USING BTREE
) ENGINE = INNODB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `User`  (
  `uid` INT(4) NOT NULL AUTO_INCREMENT,
  `uname` CHAR(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `sex` CHAR(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `age` TINYINT(1) NULL DEFAULT NULL,
  `email` CHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `password` CHAR(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  PRIMARY KEY (`uid`) USING BTREE
) ENGINE = INNODB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = DYNAMIC;

INSERT INTO `Module` VALUES(1,'情感区','你可以在这里分享你的感情精力，或者寻找你的灵魂伴侣');
INSERT INTO `Module` VALUES(2,'捞人区','提供快速找人服务，无论他是一个陌生人，仇人，帅哥或者想象中的人');

SELECT * FROM `user`;

